rabbitmq:
  host: localhost

Console:
  spy: "true"

Channels:
  global:
    format: "[GLOBAL] {prefix} {display_name} : &f{message}"
  infinity:
    format: "[&6I&f] {prefix} {display_name} : &f{message}"
  revelation:
    format: "[&5R&f] {prefix} {display_name} : &f{message}"