name: Aurionchat
version: ${version}
main: com.mineaurion.aurionchat.bukkit.AurionChat
authors: [Yann151924]
website: https://mineaurion.com
commands:
  chat:
    aliases: [ch]
    description: "AurionChat's command to manage chat channels"

permissions:
  aurionchat.chat.colors:
    default: false
    description: Chat color

