name: Java CI
on:
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Upload bukkit to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bukkit/build/libs/AurionChat-bukkit-${{ steps.get_version.outputs.VERSION }}-all.jar
          asset_name: AurionChat-bukkit-${{ steps.get_version.outputs.VERSION }}-all.jar
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload sponge to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sponge/build/libs/AurionChat-sponge-${{ steps.get_version.outputs.VERSION }}-all.jar
          asset_name: AurionChat-sponge-${{ steps.get_version.outputs.VERSION }}-all.jar
          tag: ${{ github.ref }}
          overwrite: true