name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "ci@mineaurion.com"
          git config --local user.name "Mineaurion CI"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/pluginVersion=SNAPSHOT/pluginVersion=${REF:11}/" gradle.properties
          git add gradle.properties
          git commit -m "bump ${REF:11} for release"
          git push

      - name: Create release with Gradle
        run: ./gradlew clean build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            bukkit/build/libs/*-all.jar
            forge/build/libs/*-all.jar
            sponge/build/libs/*-all.jar